on:
  # Allow running the workflow manually
  workflow_dispatch:
  # Run the workflow when a push is made
  push:
    branches:
      - main
  # Run the workflow when a pull request is made
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      matrix:
        GOOS: [windows]
        arch: [x64, x86]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: ${{ matrix.arch }}
          cache: 'pip'
          cache-dependency-path: |
              **/requirements*.txt

      - name: Install requirements
        run: |
          pip install -r ./requirements.txt -r ./singbox_subscribe/requirements.txt

      - run: pyinstaller --noconfirm --onefile --console -i "NONE" -p ./singbox_subscribe ./subconverter.py
      
      - name: Set Environment Variables
        id: set_vars
        shell: pwsh
        run: |
          if ("${{ matrix.arch }}" -eq "x64") {
            echo "::set-output name=arch::amd64"
          } else {
            echo "::set-output name=arch::386"
          }

      - uses: actions/upload-artifact@v3
        env:
          FILE_NAME: subconverter-${{ matrix.GOOS }}-${{ steps.set_vars.outputs.arch }}.exe
        with:
          name: ${{ env.FILE_NAME }}
          path: ./dist/subconverter.exe